"""add rel

Revision ID: 59afa9581074
Revises: df839acaae43
Create Date: 2021-12-10 19:56:19.871416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59afa9581074'
down_revision = 'df839acaae43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
